### ISSUE TITLE
`error: unable to instantiate class Gradlekotlinconverter`

### ISSUE THREAD

**Issue by victory1908** [bernaferrari/GradleKotlinConverter#11]
Hi tried to use the tool but after download and run the command  `./gradlekotlinconverter.kts build.gradle` i got the error:

`error: unable to instantiate class Gradlekotlinconverter (gradlekotlinconverter.kts): java.lang.NoClassDefFoundError: kotlin/script/templates/standard/ScriptTemplateWithArgs`

Any suggestion to resolve it? thanks!

**Comment by bernaferrari** [comment]
I am currently traveling, I don't know what's going on.

But, please try to copy the build.gradle and open the tool, then paste. Should be a good workaround.

**Comment by n1k3c** [comment]
@victory1908 try to install `kscript` and run `kscript gradlekotlinconverter.kts build.gradle`

**Comment by natanfudge** [comment]
This is still a problem (even though there are workarounds)

**Comment by bernaferrari** [comment]
Hello, sorry for the long wait. My email is now a chaos (RIP Inbox).
I just tested here without any issues. I don't even have `kscript` installed anymore, it was just `kotlinc -script`. Are you sure you have Kotlin installed in CLI? Just call `brew install kotlin` in macOS.

**Comment by natanfudge** [comment]
I am on Windows, I do have it on the PATH, and I get the same error.

**Comment by bernaferrari** [comment]
Check this:
https://discuss.kotlinlang.org/t/executing-kotlin-script-from-terminal/14019/2
https://github.com/holgerbrandl/kscript/issues/15

**Comment by bernaferrari** [comment]
It seems this was fixed in one of Kotlin releases. Closing.
