### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [bernaferrari/GradleKotlinConverter#13]
Can you please provide clear instruction about how to use it

**Comment by bernaferrari** [comment]
Hey! Sorry for taking so long to answer.

If you have a gradle file you would like to convert, just use

```
$ ./gradlekotlinconverter.kts build.gradle
or
$ kotlinc -script gradlekotlinconverter.kts build.gradle
```
if you want to copy the gradle file, convert, then paste, you just call

```
$ ./gradlekotlinconverter.kts
```

Is this clear? You only need to have Kotlin installed (brew install kotlin).

**Comment by NurseyitTursunkulov** [comment]
Thanks
