### ISSUE TITLE
Problem with convert "versionCode 1 + android.defaultConfig.versionCode"

### ISSUE THREAD

**Issue by dashezup** [bernaferrari/GradleKotlinConverter#25]
`versionCode 1 + android.defaultConfig.versionCode` is converted to `versionCode = android.defaultConfig.versionCode` which is wrong.

Example
https://developer.android.com/studio/build/build-variants#flavor-dimensions

btw Do you know how to write it in Gradle Kotlin DSL?

**Comment by dashezup** [comment]
Figured out a solution
`versionCode = 1 + android.defaultConfig.versionCode!!.toInt()`

**Comment by bernaferrari** [comment]
Uhhh sorry for the late reply. It seems that property could be null.. I'm not sure what I can do. Should the script take care of it?

**Comment by dashezup** [comment]
idk, don't know about Kotlin and asked a friend who figured that solution for me.
I just need to edit kotlin DSL script, find out that there are lack of documentation/examples and find this project.
If the property was null, then wouldn't the original gradle DSL invalid?
Update readme about version code addition/subtraction maybe? Or ignore that and close this issue.
