### ISSUE TITLE
Shebang

### ISSUE THREAD

**Issue by xyproto** [bernaferrari/GradleKotlinConverter#26]
Hi,

I'm on Arch Linux using Kotlin 1.4.0.

If I run `./gradlekotlinconverter.kts` I get this error message:

    usr/bin/env: 'kotlinc -script': No such file or directory
    /usr/bin/env: use -[v]S to pass options in shebang lines

But if I change the first line in `gradlekotlinconverter.kts` from this:

    #!/usr/bin/env kotlinc -script

to this:

    #!/usr/bin/kotlinc -script

it works!

**Comment by bernaferrari** [comment]
uh oh! I guess it is something from the OS? macOS needs to run the 1st one. :(

**Comment by xyproto** [comment]
It also works here with:

    #!/usr/bin/env -S kotlinc --script

Does that also work on macOS?

**Comment by bernaferrari** [comment]
Yes! That's weird, what that -S is supposed to do?

**Comment by xyproto** [comment]
It splits up the string so that `env` doesn't look for an executable that is named `kotlinc -script` (including the space), but rather looks for an executable named `kotlinc` together with an argument that is `-script`.

**Comment by bernaferrari** [comment]
Closed with https://github.com/bernaferrari/GradleKotlinConverter/commit/24614a839defe5c494a3a9904abd40e3d8da0d94. Thanks!
