### ISSUE TITLE
Issue when converting root build.gradle file on configurations.classpath.exclude    

### ISSUE THREAD

**Issue by ColtonIdle** [bernaferrari/GradleKotlinConverter#3]
Thanks for the tool!

In the readme and on reddit you state that this won't magically convert everything perfectly, so I understand if this isn't something you intend to fix. I did want to point out an issue I had when converting my root build.gradle file.

I had a line:

`configurations.classpath.exclude group: 'com.android.tools.external.lombok'`

inside of the `buildscript { }` block. It converted it to this

`configurations.classpath.exclude group: "com.android.tools.external.lombok"`

which doesn't compile. Admittedly, I didn't try too long to fix it, but I wanted to point it out here. Maybe you know what's missing here.

**Comment by bernaferrari** [comment]
Haha! No, I don't. I mean, I made this tool because gradle is hard and I didn't know everything. I'm currently in vacation, I'll be back in about a week. If you are urgent, I recommend looking for what I said on issue #2.

**Comment by ColtonIdle** [comment]
Will do. Thanks. I'll reply here if I get it figured out.

**Comment by ColtonIdle** [comment]
@bernaferrari I got a response here: https://github.com/gradle/kotlin-dsl/issues/1313

Hopefully you can add this to your script in a generic way!

**Comment by bernaferrari** [comment]
I'll add this when I get back. Thanks!!

**Comment by bernaferrari** [comment]
Added! Hope you enjoy!
