### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JahongirmirzoDv** [bernaferrari/GradleKotlinConverter#49]
how do i use this tool

**Comment by bernaferrari** [comment]
You download it, then run
```
File mode:
$ ./gradlekotlinconverter.kts build.gradle
$ kotlinc -script gradlekotlinconverter.kts build.gradle

Clipboard mode:
$ ./gradlekotlinconverter.kts
```
With clipboard, you copy, run the script, the output will be saved on clipboard, you paste where you want.

**Comment by JahongirmirzoDv** [comment]
Can you give an example of how to save it as a file?

**Comment by bernaferrari** [comment]
`./gradlekotlinconverter.kts build.gradle` it will output `build.gradle.kts`

**Comment by JahongirmirzoDv** [comment]
for this do i need to specify the build.gradle file in my project

**Comment by bernaferrari** [comment]
yes

**Comment by JahongirmirzoDv** [comment]
Thank you very much, I wish you success in your work
