### ISSUE TITLE
Test the conversions

### ISSUE THREAD

**Issue by pavi2410** [bernaferrari/GradleKotlinConverter#7]
While I was adding support for conversion of Groovy's array syntax `[items...]` to Kotlin's `listOf(items...)`, the resultant output didn't look nice because of the later steps.

We should do proper testing of each and every function separately and also as a whole.

**Comment by bernaferrari** [comment]
I am open to ideas. I think no one has ever tested kotlin scripts. Should we give up and start using gradle?

**Comment by bernaferrari** [comment]
We now have tests! https://github.com/bernaferrari/GradleKotlinConverter/actions/runs/58248489

It basically is the same as 
```
kotlinc -script gradlekotlinconverter.kts test_build_gradle skipintro && diff test_build_gradle.kts expected_build_gradle.kts
```

**Comment by pavi2410** [comment]
Thanks for the tests! I will try to fix the tasks conversion. These tests will surely help me :)

**Comment by bernaferrari** [comment]
I still need to figure out how to test the methods individually, but I got so happy already. Even github actions is working.
